language: python
python:
  - "3.4"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install cx_Freeze

script:
  - python -m unittest tests
  - python setup.py build

